# Урок 4



Задача № 1:
 
Пользователь вводит номер месяца (от 1 до 12). Вывести название сезона года на экран (зима, весна, лето, осень);

Sample Input:
12

Sample Output:
Зима


In [4]:
MonthNumber=int(input("Введите номер месяца(число от 1 до 12:"))
if (MonthNumber==1 or MonthNumber==2 or MonthNumber==12):
    print("Зима")
elif (MonthNumber==3 or MonthNumber==4 or MonthNumber==5):
    print("Весна")
elif (MonthNumber==6 or MonthNumber==7 or MonthNumber==8):
    print("Лето")
elif (MonthNumber==9 or MonthNumber==10 or MonthNumber==11):
    print("Осень")
elif(MonthNumber<1 or MonthNumber>12):
    print("Введенное число не является номером месяца")

Введите номер месяца(число от 1 до 12:12
Зима


Задача № 2:
 
Пользователь вводит число. Программа должна проверить делится ли число на 6.

Sample Input:
12

Sample Output:
Делится

Sample Input:
23

Sample Output:
Не делится



In [1]:
MyNumber=int(input("Введите число и узнайте делится ли оно на шесть:"))
if(MyNumber%6==0):
    print("Делится")
else:
    print("Не делится")

Введите число и узнайте делится ли оно на шесть:23
Не делится


Цель задания
В данном задании целью является первоначальная практика и работа, как с кодом, так и с пользовательской строкой. Также в этих заданиях мы работаем с функцией кратности (%) и определением переменных и сравнение их с тем, что ввёл пользователь.
 
План выполнения

Задать условия задачи так, чтобы выполнялись условия домашнего задания, опираясь на предыдущие изученные видео. Не забывайте, что в Вашем распоряжении есть такие символы, как: ==, or, and, >=, <= и так далее.
Задайте функцию вывода
 
Убедитесь, что выполняются все задачи домашнего задания и используются только те параметры, которые для него нужны. Например, если Вы используете символы >= в первом задании, то под Ваши условия не попадает “0”.
 
В задании №2 нужно лишь указать одно условие, которое уже было указано, это кратность (%)


# Урок 6


Напишите программу перевода введенного веса в граммы, килограммы, тонны. Приставки, которые будет использовать программа: g – граммы, kg – килограммы, t – тонны.

Sample Input:
12kg
 
Sample Output:
12000g
 
0.012t


In [5]:
#получаем исходную строку
text=input("Введите вес, используя  \n t для тонн \n kg для килограммов \n t для тонн\n при этои между числовым значением и единицей измерения не делайте нпробелов \n ")
print (text)
# переворвчиваем строку
ForEdIzm=text[::-1]
# получаем первые два символа перевернутой строки для определения единиц измерения
ForEdIzm_1=ForEdIzm[:1]
ForEdIzm_2=ForEdIzm[:2]
# определяем введеную единицу изиерения 1- если граммы, 2- если килограммы, 3 - если тонны
EdIzm=0
if(ForEdIzm_1=="g"):
    EdIzm=1
elif(ForEdIzm_1=="t"):
    EdIzm=3
if(ForEdIzm_2=="gk"):
    EdIzm=2
# выделяем числовое значение
if(EdIzm==2):
    OurValue=text[:len(text)-2]
elif(EdIzm==1 or EdIzm==3):
    OurValue=text[:len(text)-1]
OurValue=float(OurValue)


# определяем выходную строку
OutString=""
if(EdIzm==1):
    OutString=OutString+ "\n"
    OutString=OutString+str(OurValue/1000)+"kg"+"\n"
    OutString=OutString+str(OurValue/1000000)+"t"+"\n"
elif(EdIzm==2):
    OutString=OutString+str(OurValue*1000)+"g"+"\n"+"\n"
    OutString=OutString+str(OurValue/1000)+"t"
elif(EdIzm==3):
    OutString=OutString+str(OurValue*1000000)+"g"+"\n"
    OutString=OutString+str(OurValue*1000)+"kg"+"\n"

print (OutString)

Введите вес, используя  
 t для тонн 
 kg для килограммов 
 t для тонн
 при этои между числовым значением и единицей измерения не делайте нпробелов 
 12kg
12kg
12000.0g

0.012t


Цель задания: В данной практической работе целью является не только работа со строкой пользователя, но и также первая работа с определением, чем является вводимые данные, также работа с изменением вывода данных. 

План выполнения
 Создайте переменную, которая будет принимать строку пользователя Преобразуйте введенное число и приставки для вывода с помощью функции elif. Задайте функцию вывода Проверьте работоспособность Вашей программы с разными приставками.



# Урок 8

Задача № 1:
 
Написать программу, которая считывает 5 чисел со стандартного ввода и выводит на экран результат их произведения.

Sample Input:
3 4 2 1 1

Sample Output:
24


In [6]:
proiz=1
for i in range(5):
    proiz= proiz*int(input("Введите " + str(i+1) + "-е число из пяти:"))
print("Произведение введеных пяти чисел равно - ",proiz)

Введите 1-е число из пяти:3
Введите 2-е число из пяти:4
Введите 3-е число из пяти:2
Введите 4-е число из пяти:1
Введите 5-е число из пяти:1
Произведение введеных пяти чисел равно -  24


Задача № 2 :
Написать программу которая получает со стандартного ввода строку и выводит на экран количество заглавных символов
Примечание: для решения можете воспользоваться специальным методом isupper()

Sample Input:
Hello, ToM. I aM haPPy.

Sample Output:
7


In [7]:
HowManyUpperLetters=0
text=input("Введите истроку, в которой будет подсчитано количество заглавных букв:")
for j in range(0,len(text)):
    if text[j].isupper():
        HowManyUpperLetters+=1
print("Количество заглавных букв в введенной строке равно - ", HowManyUpperLetters)

Введите истроку, в которой будет подсчитано количество заглавных букв:Hello, ToM. I aM haPPy
Количество заглавных букв в введенной строке равно -  7


Цель задания  
В первом задании нужно принять пять чисел, которые введет пользователь. Перемножить эти числа и вывести результат этого произведения.                                              Во втором задании нужно принять строку пользователя и используя метод isupper сосчитать все заглавные буквы в пользовательской строке.

План выполнения

Задание №1

УСоздайте переменную, которая(ые) будет принимать строку(строки) пользователя.
Создайте функцию, которая будет перемножать вводимые пользователем числа.
Задайте функцию вывода.

Задание №2

Создайте переменную, которая будет принимать строку пользователя.
Используйте функцию isupper для счёта строки пользователя
Задайте функцию вывода


# Урок 9


Задача № 1:
 
Вам необходимо в строке, полученной со стандартного ввода найти все цифры и заменить их на букву латинского алфавита, располагающуюся по данному индексу (все символы в строке вводятся в нижнем регистре).
Примечание: две цифры не могут располагаться рядом. Те если у вас есть строка «19у» это значит что у вас одна цифра 19, а не 1 и 9. Как результат вы должны получить «sy»


Sample Input:
Hel12o 16e15ple

Sample Output:
Hello people


In [8]:
#определяем и инициализируем переменные
alpf="0abcdefghijklmnopqrstuvwxyz"
MyString=input("Введите исходнкю строку:")
outString=""
inString=MyString + "#"
i=0
while i<len(inString)-1:
    FirstSubString=inString[i]
    SecondSubString=inString[i:(i+2)]
    FirstIsNumber=FirstSubString.isdigit()
    SecondIsNumber=SecondSubString.isdigit()
    if(FirstIsNumber and SecondIsNumber):
        outString=outString+alpf[int(SecondSubString)]
        i+=2
    elif(FirstIsNumber and not(SecondIsNumber)):
        outString=outString+alpf[int(FirstSubString)]
        i+=1
    else:
        outString=outString+inString[i]
        i+=1
print("Преобразованная строка выглядит следующим образом - "+outString)

Введите исходнкю строку:Hel12o 16e15ple
Преобразованная строка выглядит следующим образом - Hello people


Задача № 2:
Вам необходимо в строке, полученной со стандартного ввода, найти повторяющиеся символы (одинаковые символы, стоящие рядом друг с другом) и заменить их на один такой символ.
Sample Input:
I loove Pyythhon!!!!!
Sample Output:
I love Python!


In [10]:
InString=input("Введите исходную строку:")
outString=""
inString= InString + "#"
i=0
while i<(len(inString)-1):
    if(inString[i]==inString[i+1]):
        i+=1
    else:
        outString+=inString[i]
        i+=1
print("Преобразованная строка - "+outString)

Введите исходную строку:I loove Pyythhon!!!!! 
Преобразованная строка - I love Python! 


Цель задания
Данные домашние задания будут немного сложнее, где уже требуется не только работа с видео лекцией, но и с посторонними источниками. От Вас уже требуется не только считать строку пользователя, но и преобразовать её. В Данном случае будет преобразование цифр в строке пользователя на буквы, которые будут заданы в программе, так и работа с повторяющимися символами, их удалением и последующим выводом получившегося результата.

План выполнения

            Задача №1

Создайте переменную, которая будет принимать строку пользователя.
Создайте алфавит
Задайте условия преобразования цифр в заданные выше алфавитом буквы.
Задайте функцию вывода
            
            Задача №2
            
Создайте переменную, которая будет принимать строку пользователя.
Создайте функцию подсчёта нескольких одинаковых символов подряд
Удалите ненужные символы
Задайте функцию вывода


# Урок 10


Создайте список чисел от 10 до 45 с шагом 5

Используя цикл while выведите на экран числа от 1 до 5

Дана строка “123467”, но в ней пропущена одна цифра. Использую функцию, выведите на экран строку со вставленной цифрой.

Дана строка “Если долго будешь писать на питоне - начнёшь говорить со змеями”. Нужно вывести на экран количество букв “о”
 


In [11]:
OurList=list(range(10,50,5))
print(OurList)

[10, 15, 20, 25, 30, 35, 40, 45]


In [12]:
i=1
while i<6:
    print (i)
    i+=1

1
2
3
4
5


In [13]:
OurString="123467"
OurList=list(OurString)
OurList.insert(4,"5")
#OutString="".join(OurList)
print("".join(OurList))

1234567


In [14]:
OurString="Если долго будешь писать на питоне - начнёшь говорить со змеями"
#OurList=list(OurString)
MyNumber=0
for i in(range(0,len(OurString))):
    if (OurString[i]=="о"):
        MyNumber+=1
print ("Количество букв -о- в заданной строке равно - ", MyNumber)

Количество букв -о- в заданной строке равно -  6


Цель задания
В данных заданиях будет проводиться работа с уже заданной строкой, поэтому не нужно отвечать на все условия работы. Цель в этих заданиях научиться работать не только с числами, но и со строками. Работа будет проводится с созданием новых цифр, работа с элементами строки, вставкой элемента по индексу и так же подсчёт элементов в строке.

План выполнения

Задача №1

Напишите функцию выявления границ списка из чисел и шага для отображения.
Задайте функцию вывода

Задача №2

Используйте функцию while для того, чтобы задать цикл и определите границы цикла
Задайте функцию вывода

Задача №3

Создайте переменную в которой будет заданная строка
Используйте функцию вставки нужной цифры по индексу
Задайте функцию вывода

Задача №4

Создайте переменную в которой будет заданная строка
Создайте функцию, в которой будет подсчёт нужного символа
Задайте функцию вывода




# Урок 13


Даны два параметра вывода “Я ученик”. Используя функцию def выведите на экран “Я лучший ученик Синергии!”


Даны числа “2, 4, 6, 8, 10”. В этом списке нужно выписать все числа кратные “4” и умножить их на 2. Вывести на экран.


In [15]:
MyInputString="Я ученик"
def MySolutionToTaskOne(InString):
    MyList=InString.split()
    MyList.insert(1,"лучший")
    MyList.append("Синергии")
    return(MyList)

OutList=MySolutionToTaskOne(MyInputString)
OutString=""
for i in(OutList):
    OutString+=i+" "
print (OutString)

Я лучший ученик Синергии 


In [17]:
MyInputString="2, 4, 6, 8, 10"
MyList=MyInputString.split(", ")

for item in MyList[::-1]:
    if int(item)%4==0:
        i=MyList.index(item)
        MyList[i]=str(int(item)*2)
    else:
         MyList.remove(item)
print(MyList)

['8', '16']


Цель задания
В данном задании мы учимся работать с функцией def и работа с заданной строкой.

План выполнения

Задача №1

Задайте переменную в которой будет находится заданные слова.
Используйте функцию def, для того чтобы работать с индексом и вставкой новых данных
Задайте функцию вывода

Задача №2

Создайте переменную, в которой будут находится заданные цифры
Задайте функцию, которая будет проходить по индексу заданной строки и искать нужные цифры
Задать функции удалять не найденные цифры, а найденные умножить на 2.
Задайте функцию вывода


# Урок 16


Задача № 1:
 
Создайте словарь, где ключами и значениями будут числа от 1 до 9. Затем, с помощью этого словаря отобразите на экране таблицу умножения. Для создания словаря, воспользуйтесь генератором.

Sample Output:

   1   2   3   4   5   6   7   8   9
   
   2   4   6   8  10  12  14  16  18
   
   3   6   9  12  15  18  21  24  27
   
   4   8  12  16  20  24  28  32  36
   
   5  10  15  20  25  30  35  40  45
   
   6  12  18  24  30  36  42  48  54
   
   7  14  21  28  35  42  49  56  63
   
   8  16  24  32  40  48  56  64  72
   
   9  18  27  36  45  54  63  72  81
   
Дана строка в виде случайной последовательности чисел от 0 до 9.

In [18]:
InputString="3579840126" #строка случайной последовательности чисел от "0" до "9"
MyList=list(InputString)
MyList.sort()#сотрируем список по возрастанию
for it in (MyList): # удаляем из списка "0"
    if int(it)<1:
        MyList.remove(it)
#генератор словаря
MyDic={ int(x):int(x) for x in(MyList)}
# вывод на экран таблицы умножения
for key in (MyDic):
    for value in(MyDic):
        print(str(key*value), end="\t")
    print("\n" )



1	2	3	4	5	6	7	8	9	

2	4	6	8	10	12	14	16	18	

3	6	9	12	15	18	21	24	27	

4	8	12	16	20	24	28	32	36	

5	10	15	20	25	30	35	40	45	

6	12	18	24	30	36	42	48	54	

7	14	21	28	35	42	49	56	63	

8	16	24	32	40	48	56	64	72	

9	18	27	36	45	54	63	72	81	



Задача № 2:
 
Требуется создать словарь, который в качестве ключей будет принимать данные числа (т. е. ключи будут типом int), а в качестве значений – количество этих чисел в имеющейся последовательности. Для построения словаря создайте функцию count_it(sequence), принимающую строку из цифр. Функция должна возвратить словарь из 3-х самых часто встречаемых чисел.

Sample Input:

2122234555768290909389

Sample Output:

{2 :  5, 5 : 3, 9 : 4}


In [19]:
# определим глобальные переменные
global InDict 
global OutDict

# функция получения ключа элемента с максимальным значением
def KeyOfMaxValueDict(InDict):
    KeyOfMaxValueDict=0
    MaxVal=0
    for key in(InDict):
        if InDict[key]>MaxVal:
            MaxVal=InDict[key]
            KeyOfMaxValueDict=key
    return KeyOfMaxValueDict

# функция переноса элемента по ключу из одного словаря в другой
def ReplaceMembersofDictionary(InDict,OutDict,MyKey):
    mk=MyKey
    mv=InDict[MyKey]
    OutDict.update({mk:mv})
    InDict.pop(MyKey)

# основная функция задачи
def count_it(sequence):
    InputString=sequence

    #преобразование входных данных        
    MyList=list(InputString)
    #формируем исходный словарь
    SourseDict=dict()
    for i in(range(10)):
        col=MyList.count(str(i))
        SourseDict.update({i:col})
    KeyMax=KeyOfMaxValueDict(SourseDict)
    OutDict=dict()
    InDict=SourseDict.copy()
    ReplaceMembersofDictionary(InDict,OutDict,KeyMax)
   
    for i in(range(2)):
        NewMaxKey=KeyOfMaxValueDict(InDict)
        ReplaceMembersofDictionary(InDict,OutDict,NewMaxKey)
    return(OutDict)
    #print(OutDict)

# код основной программы
count_it("2122234555768290909389")
print(count_it("2122234555768290909389"))

{2: 5, 9: 4, 5: 3}


Цель задания

В данном задании мы учимся работать с генератором, словарём и функцией count_it(sequence) и строкой вывода для конкретного значения.

План выполнения

Задача №1

Напишите генератор, который будет содержать в себе значения от 1 до 9 по вертикали и диагонали и их перемножение с дальнейшим выводом
Задайте функцию вывода генератора на экран

Задача №2

Используя функцию count_it(sequence) задайте её свойства для подсчёта цифр
Используйте словарь, чтобы можно было определять наибольшее количество повторяющихся элементов по каждой цифре
Задайте функцию вывода


# Урок 17


Создать текстовой файл, в котором будет хранится: Приветствие, Ваше имя и Ваше направление в обучении.


In [ ]:
with open('17.txt','w',encoding='utf-8') as my_file:
    my_file.writelines("Здравствуйте!\n")
    my_file.writelines("Проскуряков Вадим\n")
    my_file.writelines("Data Scientist")

Цель задания

Является научиться создать текстовой файл, в котором будут хранится определённые данные.

План выполнения


Задайте функцию создания текстового файла
Установите параметры для отображения и сохранения определённых данных в установленном текстовом файле
 

# Урок 19


Используя библиотеку NumPy:

Создайте строку от 0 до 10

Поменяйте местами цифры 5 8

Выведите на экран два массива: первоначальный и изменённый

Объедините их

Сделайте из этой строки 3 столба
 


In [46]:
import numpy as np
MyAr1=np.array(range(11),int)
MyAr2=MyAr1.copy()
prom=MyAr2[5]
MyAr2[5]=MyAr2[8]
MyAr2[8]=prom
print("Первоначальный массив\t \t",MyAr1)
print("Измененный массив \t\t",MyAr2)
MyAr3=np.concatenate((MyAr1, MyAr2))
print("объединенный массив \t\t", MyAr3)
# для того чтобы длина строки была кратна 3-м - отбрасываем  первый ноль как незначащий
MyAr4=MyAr3[1:].reshape((7,3))
print("Три столбца из строки вариант 1(отбрасываем первый ноль как незначащий):\n",MyAr4)

# для того чтобы длина строки была кратна 3-м - добавляем два раза по 77 в конец  массива
MyAr4=np.concatenate((MyAr3,[77,77])).reshape((8,3))
print("Три столбца из строки вариант 2(добавляем два раза по 99 в конец  массива):\n",MyAr4)

# для того чтобы длина строки была кратна 3-м - отбрасываем  первый ноль как незначащий
MyAr41=MyAr3[0:8].reshape((8,1))
MyAr42=MyAr3[8:15].reshape((7,1))
MyAr43=MyAr3[15:].reshape((7,1))
print("Три столбца из строки вариант 3 - три одномерных массива с одним столбцом(8+7+7):\n1-й:",MyAr41,"\n2-й:",MyAr42,"\n3-й:",MyAr43)

Первоначальный массив	 	 [ 0  1  2  3  4  5  6  7  8  9 10]
Измененный массив 		 [ 0  1  2  3  4  8  6  7  5  9 10]
объединенный массив 		 [ 0  1  2  3  4  5  6  7  8  9 10  0  1  2  3  4  8  6  7  5  9 10]
Три столбца из строки вариант 1(отбрасываем первый ноль как незначащий):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10  0  1]
 [ 2  3  4]
 [ 8  6  7]
 [ 5  9 10]]
Три столбца из строки вариант 2(добавляем два раза по 99 в конец  массива):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10  0]
 [ 1  2  3]
 [ 4  8  6]
 [ 7  5  9]
 [10 77 77]]
Три столбца из строки вариант 3 - три одномерных массива с одним столбцом(8+7+7):
1-й: [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] 
2-й: [[ 8]
 [ 9]
 [10]
 [ 0]
 [ 1]
 [ 2]
 [ 3]] 
3-й: [[ 4]
 [ 8]
 [ 6]
 [ 7]
 [ 5]
 [ 9]
 [10]]


Цель задания

В данном задании мы научимся работать и пользоваться библиотекой NumPy.

План выполнения

Загрузите библиотеку NumPy
Используйте библиотеку NumPy для работы в домашнем задании
 

# Урок 20


Создайте класс студентов

Создайте класс предметов

Используя новый проект, загрузите данные классов и задайте примеру двух студентов и двух направлений
 


Содержание ForModul20:

In [48]:

class Student:
    def __init__(self,name,age,direction):
        self.name=name
        self.age=age
        self.direction=direction

    def ShowAboutStudent(self):
        print("Имя студента - ",self.name)
        print("Его возраст - ",self.age ,"а его направление обучения -", self.direction)
        
class Case:
    def __init__(self,name ,ForDirection,CountClasses):
        self.name=name
        self.ForDirection=ForDirection
        self.CountClasses=CountClasses
    

Решение задачи:


In [51]:
 from ForModul20 import Student,Case
FirstStudent=Student("Вадим",52,"Data Scientist")
SecondStudent=Student("Вася","Неопределен","Неизвестно")
FirstStudent.ShowAboutStudent()
SecondStudent.ShowAboutStudent()
FirstCaseDS=Case("Основы Python","Data Scientist",24)
SecondCaseDS=Case("Продвинутые коммуникационные навыки","Data Scientist",12)

FirstCaseN=Case("Основы Python","Неизвестно","Неопределенность")
SecondCaseN=Case("Продвинутые коммуникационные навыки","Неизвестно","Может быть каким угодно")

print("Для студента ",FirstStudent.name,"который учится по напрвлению ",FirstStudent.direction," по предмету ",FirstCaseDS.name," количество запланированых занятий равно ",FirstCaseDS.CountClasses)
print("Для студента ",SecondStudent.name,"который учится по напрвлению ",SecondStudent.direction," по предмету ",FirstCaseN.name," количество запланированых занятий равно ",FirstCaseN.CountClasses)


Имя студента -  Вадим
Его возраст -  52 а его направление обучения - Data Scientist
Имя студента -  Вася
Его возраст -  Неопределен а его направление обучения - Неизвестно
Для студента  Вадим который учится по напрвлению  Data Scientist  по предмету  Основы Python  количество запланированых занятий равно  24
Для студента  Вася который учится по напрвлению  Неизвестно  по предмету  Основы Python  количество запланированых занятий равно  Неопределенность


Цель задания
В данном задании мы учимся работать с классами

План выполнения

Создайте класс студентов.
Создайте класс предметов
Создайте новый файл в Python формате
Используйте функции класс из первого файла для того, чтобы вывести имена двух студентов и их направления
Задайте функцию вывода
                                                                                                             

# Урок 21


Используйте работу с прошлого задания

Добавьте в неё исключения в виде школьников и закончивших ВУЗ
 


Содержание ForModul20:

In [50]:

from asyncio import proactor_events


class Student:
    def __init__(self,name,age,direction, yearOfDiplom):
        self.__name=name
        self.__age=age
        if (len(direction)==0):
            print(self.__name,"- вообще не является студентом, так как у него отсутствует направление")
            self.__direction="Пока не студент"
        else:
            self.__direction=direction
        if (yearOfDiplom<2022):
            print(self.__name," -не является студентом так как уже закончил ВУЗ в ",yearOfDiplom," году")
            self.__yearOfDiplom="Уже не студент"
        else:
            self.__yearOfDiplom=yearOfDiplom
    def set__name(self,name):
        self.__name=name
    #@property
    def get__name(self):
        return self.__name
    def get__direction(self):
        return self.__direction
   






    def ShowAboutStudent(self):
        print("Имя студента - ",self.__name)
        print("Его возраст - ",self.__age )
        print("а его направление обучения -", self.__direction)
        print("Диплом  был/будет от ",self.__yearOfDiplom,"-го года\n")
class Case:
    def __init__(self,name ,ForDirection,CountClasses):
        self.name=name
        self.ForDirection=ForDirection
        self.CountClasses=CountClasses

#FirstStudent=Student("Вадим",52,"Data Scientist",2022)
#SecondStudent=Student("Вася","Неопределен","","")
#print(FirstStudent.direction)
#FirstStudent.ShowAboutStudent()
#SecondStudent.ShowAboutStudent()

Решение задачи:


In [52]:
from ForModul21 import Student,Case
FirstStudent=Student("Вадим",52,"Data Scientist",2022)
SecondStudent=Student("Вася","Неопределен","Никто не знает",2022)
FirstStudent.ShowAboutStudent()
SecondStudent.ShowAboutStudent()
FirstCaseDS=Case("Основы Python","Data Scientist",24)
SecondCaseDS=Case("Продвинутые коммуникационные навыки","Data Scientist",12)

FirstCaseN=Case("Основы Python","Неизвестно","Неопределенность")
SecondCaseN=Case("Продвинутые коммуникационные навыки","Неизвестно","Может быть каким угодно")


print("Для студента ",FirstStudent.get__name(),"который учится по напрвлению ",FirstStudent.get__direction()," по предмету ",FirstCaseDS.name," количество запланированых занятий равно ",FirstCaseDS.CountClasses)
print("Для студента ",SecondStudent.get__name(),"который учится по напрвлению ",SecondStudent.get__direction()," по предмету ",FirstCaseN.name," количество запланированых занятий равно ",FirstCaseN.CountClasses)
 
FirstNewStudent=Student("Ольга",20,"",2023)
SecondtNewStudent=Student("Канат",27,"Data Scientist",2020)


Имя студента -  Вадим
Его возраст -  52
а его направление обучения - Data Scientist
Диплом  был/будет от  2022 -го года

Имя студента -  Вася
Его возраст -  Неопределен
а его направление обучения - Никто не знает
Диплом  был/будет от  2022 -го года

Для студента  Вадим который учится по напрвлению  Data Scientist  по предмету  Основы Python  количество запланированых занятий равно  24
Для студента  Вася который учится по напрвлению  Никто не знает  по предмету  Основы Python  количество запланированых занятий равно  Неопределенность
Ольга - вообще не является студунтом, так как у него отсутствует направление
Канат  -не является студентом так как уже закончил ВУЗ в  2020  году
